# -*- coding: utf-8 -*-
"""Covid_19_Risk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BUFGriaIE9SRdPaQ2ndE8i_wmdUp6gyu

Problem :

Task : Estimating the risk of death from coronavirus. Write a program that;

Takes "Yes" or "No" from the user as an answer to the following questions :

Are you a cigarette addict older than 75 years old? Variable → age

Do you have a severe chronic disease? Variable → chronic

Is your immune system too weak? Variable → immune

Set a logical algorithm using boolean logic operators (and/or) and use if-statements with the given variables in order to print out us a message : "You are in risky group"(if True ) or "You are not in risky group" (if False).
"""

age = input("Are you a cigarette addict older than 75 years old?: ").title().strip()
chronic = input("Do you have a severe chronic disease?: ").title().strip()
immune = input("Is your immune system too weak?: ").title().strip()

if age == "Yes" or chronic == "Yes" or immune == "Yes":
  print("You are in risky group")
else: 
  print("You are not in risky group")