# -*- coding: utf-8 -*-
"""Copy of password_task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n_-tFPPkLVgyhTd_FfLzdXtUK9HQidZL
"""

# Task : Let's say; you left a message in the past that prints a password you 
# need. To see the password you wrote, you need to enter your name 
# and the program should recognize you.

# Write a program that 

# 1. Takes the first name from the user and compares it to yours,
# 2. Then if the name the user entered is the same as yours, print 
#out such as : "Hello, Joseph! The password is : W@12",
# 3. If the name the user entered is not the same as yours, 
# print out such as : "Hello, Amina! See you later."



name_requested = input("Please enter your name here: ").title().split()

name = "Fatma"

if name_requested[0] == name:
  print("Hello, Fatma! The password is : W@12")
else: 
  print(f"Hello, {name_requested[0]}! See you later.")